### ISSUE TITLE
Display recently active plugins

### ISSUE THREAD

**Issue by dartiss** [dartiss/plugins-list#34]
Am I able to find/work out which plugins were recently active.

If this information isn't available as-is, I may have to work it out, using the same method that WP core does - inc. how long "recently" is.

Requested here: https://wordpress.org/support/topic/recently-active-plugins/

**Comment by stefanpejcic** [comment]
WP core uses

```
               foreach ( $recently_activated as $key => $time ) {
			if ( $time + WEEK_IN_SECONDS < time() ) {
				unset( $recently_activated[ $key ] );
			}
		}

		if ( $screen->in_admin( 'network' ) ) {
			update_site_option( 'recently_activated', $recently_activated );
		} else {
			update_option( 'recently_activated', $recently_activated );
		}
```

So you could get the plugins directly from `wp_options > recently_activated` ?

https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-wp-plugins-list-table.php

**Comment by dartiss** [comment]
I've been looking at this and it's... difficult.

The format of the array returned is `[plugin-name/plugin-file.php]`. If I had this I'd have to process each plugin and check this array before outputting it.

The next release of the plugin will load an array of recently active plugins as `$recently_activated()`

**Comment by dartiss** [comment]
YES. I worked it out. Now added for next release.
