### ISSUE TITLE
Inactive plugins showing always

### ISSUE THREAD

**Issue by reszel** [dartiss/plugins-list#54]
Shortcode: 
[plugins_list format="{{LinkedTitle}} - {{Version}} - ({{LinkedAuthor}}) - {{Description}}{{br/}}" show_active=true show_inactive=false]
My page: https://wp.rebbe.se/plugins-list/

**Comment by dartiss** [comment]
I can't recreate this at all, even using your shortcode.

Can you confirm which version of the plugin you're using? Also, can you put that shortcake on a page by itself and share that?

**Comment by reszel** [comment]
Thanx! All is Well! Just installed new plugin and the Error is gone!
PS. Shortcode:
[plugins_list format="{{Active}}: the minimum required level of PHP: {{RequiresPHP}}, the minimum required level of WordPress: {{RequiresWP}} {{br/}} {{LinkedTitle}} - {{Version}} - ({{LinkedAuthor}}){{br/}}" cache=false]
